// Error Lookup
// Copyright (c) 2011-2015 Henry++

#ifndef __MAIN_H__
#define __MAIN_H__

#include <windows.h>
#include "resource.h"

// config
#define APP_NAME L"Error Lookup"
#define APP_NAME_SHORT L"errorlookup"
#define APP_VERSION L"2.1.1247"
#define APP_VERSION_RES 2,1,1247,0
#define APP_COPYRIGHT L"(c) 2011-2016 " _APP_AUTHOR L". All Rights Reserved."

// libs
#pragma comment(lib, "dxerr.lib")
#pragma comment(lib, "version.lib")

// sev.
#define STATUS_SEVERITY_SUCCESS 0
#define STATUS_SEVERITY_INFORMATIONAL 1
#define STATUS_SEVERITY_WARNING 2
#define STATUS_SEVERITY_ERROR 3

// fac. codes (directx sdk)
#define FACILITY_CODCLASS_ERROR_CODE 6
#define FACILITY_VIDEO 27
#define FACILITY_FILTER_MANAGER 28
#define FACILITY_MONITOR 29
#define FACILITY_GRAPHICS_KERNEL 30
#define FACILITY_WIN32K_NTUSER 62
#define FACILITY_WIN32K_NTGDI 63
#define FACILITY_RESUME_KEY_FILTER 64
#define FACILITY_RDBSS 65
#define FACILITY_BTH_ATT 66
#define FACILITY_SECUREBOOT 67
#define FACILITY_AUDIO_KERNEL 68
#define FACILITY_VOLSNAP 80
#define FACILITY_SHARED_VHDX 92
#define FACILITY_INTERIX 153
#define FACILITY_SPACES 231
#define FACILITY_EAP_MESSAGE 2114
#define FACILITY_D3D 2166
#define FACILITY_D3DX 2167
#define FACILITY_DSOUND_DMUSIC 2168
#define FACILITY_D3D10 2169
#define FACILITY_D3D11_OR_AE 2172
#define FACILITY_APO 2173
#define FACILITY_XAUDIO2 2198
#define FACILITY_XAPO 2199
#define FACILITY_DWRITE 2200
#define FACILITY_D2D 2201
#define FACILITY_WSAPI 2185
#define FACILITY_XACTENGINE 2759

// fac. codes (win8 sdk)
#define FACILITY_XAML 43
#define FACILITY_USN 129
#define FACILITY_BLBUI 128
#define FACILITY_SPP 256
#define FACILITY_WSB_ONLINE 133
#define FACILITY_DLS 153
#define FACILITY_BLB_CLI 121
#define FACILITY_BLB 120
#define FACILITY_WSBAPP 122
#define FACILITY_WPN 62
#define FACILITY_WMAAECMA 1996
#define FACILITY_WINPE 61
#define FACILITY_WINCODEC_DWRITE_DWM 2200
#define FACILITY_WIA 33
#define FACILITY_WER 27
#define FACILITY_WEB_SOCKET 886
#define FACILITY_WEB 885
#define FACILITY_USERMODE_VOLSNAP 130
#define FACILITY_USERMODE_VOLMGR 56
#define FACILITY_VISUALCPP 109
#define FACILITY_USERMODE_SPACES 231
#define FACILITY_SOS 160
#define FACILITY_RESTORE 256
#define FACILITY_SCRIPT 112
#define FACILITY_PARSE 113
#define FACILITY_POWERSHELL 84
#define FACILITY_PIDGENX 2561
#define FACILITY_P2P_INT 98
#define FACILITY_P2P 99
#define FACILITY_ONLINE_ID 134
#define FACILITY_NAP 39
#define FACILITY_MOBILE 1793
#define FACILITY_LINGUISTIC_SERVICES 305
#define FACILITY_LEAP 2184
#define FACILITY_ACCELERATOR 1536
#define FACILITY_EAS 85
#define FACILITY_EAP 66
#define FACILITY_DXGI_DDI 2171
#define FACILITY_DXGI 2170
#define FACILITY_DMSERVER 256
#define FACILITY_DIRECTMUSIC 2168
#define FACILITY_DIRECT3D11 2172
#define FACILITY_DIRECT3D10 2169
#define FACILITY_DIRECT2D 2201
#define FACILITY_DAF 100
#define FACILITY_DEPLOYMENT_SERVICES_UTIL 260
#define FACILITY_DEPLOYMENT_SERVICES_TRANSPORT_MANAGEMENT 272
#define FACILITY_DEPLOYMENT_SERVICES_TFTP 264
#define FACILITY_DEPLOYMENT_SERVICES_PXE 263
#define FACILITY_DEPLOYMENT_SERVICES_MULTICAST_SERVER 289
#define FACILITY_DEPLOYMENT_SERVICES_MULTICAST_CLIENT 290
#define FACILITY_DEPLOYMENT_SERVICES_MANAGEMENT 259
#define FACILITY_DEPLOYMENT_SERVICES_IMAGING 258
#define FACILITY_DEPLOYMENT_SERVICES_DRIVER_PROVISIONING 278
#define FACILITY_DEPLOYMENT_SERVICES_SERVER 257
#define FACILITY_DEPLOYMENT_SERVICES_CONTENT_PROVIDER 293
#define FACILITY_DEPLOYMENT_SERVICES_BINLSVC 261
#define FACILITY_DEFRAG 2304
#define FACILITY_DEBUGGERS 176
#define FACILITY_BLUETOOTH_ATT 101
#define FACILITY_AUDIOSTREAMING 1094
#define FACILITY_AUDCLNT 2185
#define FACILITY_AUDIO 102

// fac. codes (win8.1 sdk)
#define FACILITY_WEP 2049
#define FACILITY_TIERING 131
#define FACILITY_SYNCENGINE 2050
#define FACILITY_USERMODE_SDBUS 2305
#define FACILITY_JSCRIPT 2306
#define FACILITY_ACTION_QUEUE 44

// fac. codes (win10 sdk)
#define FACILITY_XBOX 2339
#define FACILITY_UTC 1989
#define FACILITY_STATEREPOSITORY 103
#define FACILITY_SQLITE 1967
#define FACILITY_USER_MODE_SECURITY_CORE 232
#define FACILITY_USERMODE_LICENSING 234
#define FACILITY_DIRECT3D12_DEBUG 2175
#define FACILITY_DIRECT3D12 2174
#define FACILITY_DIRECT3D11_DEBUG 2173
#define FACILITY_DELIVERY_OPTIMIZATION 208

// routine
#define SWITCH_ROUTINE(x) case x: buffer.Format(L"%s (0x%02x)", L#x, x); break;

#endif // __MAIN_H__
