#ifndef __RESOURCE_H__
#define __RESOURCE_H__

#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

// Acceleration
#define IDA_MAIN 1

// Dialogs
#define IDD_MAIN 100

// Main Dlg
#define IDC_CODE 100
#define IDC_CODE_CTL 101
#define IDC_CODE_UD 102
#define IDC_LISTVIEW 103
#define IDC_DESCRIPTION 104
#define IDC_DESCRIPTION_CTL 105
#define IDC_STATUSBAR 106

// Main Menu
#define IDM_EXIT 1000
#define IDM_ALWAYSONTOP_CHK 1001
#define IDM_INSERTBUFFER_CHK 1002
#define IDM_CHECKUPDATES_CHK 1003
#define IDM_ADDMODULE 1004
#define IDM_WEBSITE 1005
#define IDM_CHECKUPDATES 1006
#define IDM_ABOUT 1007
#define IDM_ZOOM 1008

#define IDX_MODULES 2000
#define IDX_LANGUAGE 3000

// Strings
#define IDS_LCID 1

#define IDS_UPDATE_NO 2
#define IDS_UPDATE_YES 3

#define IDS_FILE 4
#define IDS_SETTINGS 5
#define IDS_EXIT 6
#define IDS_LANGUAGE 7
#define IDS_HELP 8
#define IDS_WEBSITE 9
#define IDS_CHECKUPDATES 10
#define IDS_ABOUT 11
#define IDS_DONATE 12

#define IDS_ALWAYSONTOP_CHK 13
#define IDS_INSERTBUFFER_CHK 14
#define IDS_CHECKUPDATES_CHK 15

#define IDS_CODE 16
#define IDS_MODULES 17
#define IDS_DESCRIPTION 18
#define IDS_INFORMATION 19

#define IDS_STATUS_TOTAL 20
#define IDS_STATUS_EMPTY 21
#define IDS_STATUS_EMPTY2 22

// Icons
#define IDI_MAIN 100

#endif // __RESOURCE_H__
